=== Predictly/axel/shs/shs-protocol/src/main/resources/dtd/shs-label-1.2.01.dtd
<!--

    Copyright (C) 2013 Inera AB (http://www.inera.se)

    This file is part of Inera Axel (http://code.google.com/p/inera-axel).

    Inera Axel is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Inera Axel is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>

-->
<!ELEMENT	shs.label	(((originator, from?) | from), to?,
							end-recipient?, product, meta*, subject?,
							datetime, content, history*)>
<!ATTLIST shs.label
	version CDATA #FIXED "1.2"
	tx.id NMTOKEN #REQUIRED
	corr.id NMTOKEN #REQUIRED
	shs.agreement NMTOKEN #IMPLIED
	transfer-type (asynch | synch) "asynch"
	message-type (simple | compound) "simple"
	document-type (simple | compound) "simple"
	sequence-type (event | request | reply | adm) #REQUIRED
	status (test | production) "production"
>
<!ELEMENT originator (#PCDATA)>
<!ATTLIST originator
	name CDATA #IMPLIED
	labeledURI CDATA #IMPLIED
>
<!ELEMENT from (#PCDATA)>
<!ATTLIST from
	commonName CDATA #REQUIRED
	e-mail CDATA #IMPLIED
	labeledURI CDATA #IMPLIED
>
<!ELEMENT to (#PCDATA)>
<!ATTLIST to
	commonName CDATA #IMPLIED
>
<!ELEMENT end-recipient (#PCDATA)>
<!ATTLIST end-recipient
	name CDATA #IMPLIED
	labeledURI CDATA #IMPLIED
>
<!ELEMENT product (#PCDATA)>
<!ATTLIST product
	commonName CDATA #IMPLIED
	labeledURI CDATA #IMPLIED
>
<!ELEMENT meta (#PCDATA)>
<!ATTLIST meta
	name CDATA #REQUIRED
>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT datetime (#PCDATA)>
<!ELEMENT content ((data* | compound), comment?)>
<!ATTLIST content
	content.id NMTOKEN #REQUIRED
>
<!ELEMENT data EMPTY>
<!ATTLIST data
	datapartType CDATA #REQUIRED
	filename CDATA #IMPLIED
	no-of-bytes NMTOKEN #IMPLIED
	no-of-records NMTOKEN #IMPLIED
>
<!ELEMENT compound EMPTY>
<!ATTLIST compound
	no-of-parts NMTOKEN #REQUIRED
>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT history (datetime, comment?)>
<!ATTLIST history
	node.id NMTOKEN #REQUIRED
	content.id NMTOKEN #IMPLIED
	tx.id NMTOKEN #IMPLIED
	from CDATA #IMPLIED
	to CDATA #IMPLIED
	local.id NMTOKEN #IMPLIED
	shs.agreement NMTOKEN #IMPLIED
>

=== Predictly/axel/shs/shs-broker-synchron/src/test/testdata/shs-label-sync-public-agreement-addr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2013 Inera AB (http://www.inera.se)

    This file is part of Inera Axel (http://code.google.com/p/inera-axel).

    Inera Axel is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Inera Axel is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>

-->
<!DOCTYPE shs.label SYSTEM "../../../../shs-protocol/src/main/resources/dtd/shs-label-1.2.01.dtd" >
<shs.label corr.id="nmtoken" 
	document-type="simple" message-type="simple" sequence-type="request"
	status="production" transfer-type="synch" tx.id="nmtoken" version="1.2">
	
  <originator name="R2M">urn:X-shs:orgno:556531-7129</originator>
  <from commonName="R2M">urn:X-shs:5565317129</from>
  
  <to commonName="R2M"></to>
  <end-recipient labeledURI="" name="Unknown">Unknown</end-recipient>
  
  <product commonName="Internal Invoice" labeledURI="">urn:X-shs:545b12e0-f020-11e1-aff1-0800200c9a66</product>
  
  <meta name="InvoiceDate">2012-08-22</meta>
  <meta name="IssuedBy">GhostBusters</meta>
  
  <subject>Busting fee</subject>
  <datetime>2012-08-22T08:15:00</datetime>
  
  <content content.id="nmtoken">
    <data datapartType="pdf" filename="invoice.pdf" no-of-bytes="200000" no-of-records="1"/>
    <comment>comment</comment>
  </content>
  
  <history content.id="nmtoken" from="" local.id="nmtoken" node.id="nmtoken" shs.agreement="nmtoken" to="" tx.id="nmtoken">
    <datetime>datetime</datetime>
    <comment>comment</comment>
  </history>
</shs.label>
